# AvalOS — MangoHUD config (Tokyo Night)
# Actívalo en cualquier juego con: MANGOHUD=1 %command%
# O en Steam: agrega "MANGOHUD=1 %command%" en opciones de lanzamiento

legacy_layout=0
position=top-left
width=260
height=150

# ── Qué mostrar ───────────────────────────────────────────────────
fps
fps_limit=0
frame_timing=1
frametime
cpu_stats
cpu_temp
gpu_stats
gpu_temp
gpu_power
vram
ram
wine
engine_version

# ── Aspecto — Tokyo Night ──────────────────────────────────────────
background_alpha=0.7
font_size=20
font_size_text=16
text_color=c0caf5
background_color=1a1b26
gpu_color=7aa2f7
cpu_color=9ece6a
fps_color_change=1
fps_value=30,60
fps_color=f7768e,e0af68,9ece6a

# ── Comportamiento ────────────────────────────────────────────────
no_display=0
toggle_hud=Shift_R+F12
toggle_fps_limit=Shift_R+F1
reload_cfg=Shift_R+F4
upload_log=Shift_R+F3
